### ISSUE TITLE
'COPYING' is not properly recognized by github 

### ISSUE THREAD

**Issue by jeanguyomarch** [jbrv/dprpwg#2]
I am aware that 'COPYING' is a recommended naming convention of the FSF, but GitHub expects the license file to be either `LICENSE` or `LICENSE.md` (as explained here: https://help.github.com/articles/adding-a-license-to-a-repository/).

I believe conforming to the GitHub convention will provide a better use experience when browsing this repository, as the type of the license will be directly integrated within the repository's GUI.

**Comment by jbrv** [comment]
Mm... Strange...

I tried the advices given by your link; at the step where you should put the file name, it indeed says to name it `LICENSE` or `LICENSE.md`, so a "Choose a license template" button appears.
If I put `COPYING`, this button also appears, so it looks like the `COPYING` file name is somewhat recognized...

... will check that, either the name or the content of the file is not correct, I did not use GitHub templates...

**Comment by jbrv** [comment]
`COPYING` file name is definitely recognized by the GitHub [`licensee`](https://github.com/benbalter/licensee/blob/d81cc3273403aada1c6314b32bf6cf4c0835e960/lib/licensee/project_files/license_file.rb#L29) tool. Must be an issue with the content...

**Comment by jeanguyomarch** [comment]
I guess, if you are certain that this is indeed used by GitHub, at this given version.
